name: Enforce Source Branch - Stage

on:
  pull_request:
    branches:
      - stage

jobs:
  check-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" != "qa" ]]; then
            echo "Only merges from 'qa' to 'stage' are allowed."
            exit 1
          fi
