name: Enforce Source Branch - Main

on:
  pull_request:
    branches:
      - main

jobs:
  check-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" != "stage" ]] && ! [[ "${{ github.head_ref }}" =~ ^hotfix/.* ]]; then
            echo "Only merges from 'stage' or 'hotfix/*' to 'main' are allowed."
            exit 1
          fi
