name: Enforce Source Branch - QA

on:
  pull_request:
    branches:
      - qa

jobs:
  check-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" != "develop" ]]; then
            echo "Only merges from 'develop' to 'qa' are allowed."
            exit 1
          fi
